Importando librerias

In [1]:
import numpy as np
import matplotlib.pyplot as plt


Solución del problema:
1.a

Genero las ecuaciones

In [17]:
A_1 = np.array([[2, 4, 5], [6, 9, 8], [4.1, 5, 3]])
B_1 = np.array([220, 490, 274])

Se le saca la inversa A y luego se multiplica por la misma matriz A, para sacar la matriz de identidad

In [40]:
# Get the inverse of A
A_inv_1 = np.linalg.inv(A_1)

# Multiply the inverse of A by A
result = np.dot(A_inv_1, A_1)

# Print the result
print(result)

[[ 1.00000000e+00 -7.10542736e-15 -7.10542736e-15]
 [-9.70164120e-16  1.00000000e+00  1.24344979e-14]
 [ 4.03096360e-16 -8.88178420e-16  1.00000000e+00]]


Multiplico la inversa de la Matriz A, por el vector B (Igualdad)

In [21]:
X_1 = np.linalg.inv(A_1).dot(B)
X_1

array([40., 10., 20.])

In [22]:
print("The price per hour in processor A is:", X_1[0])
print("The price per hour in processor B is:", X_1[1])
print("The price per hour in processor C is:", X_1[2])

The price per hour in processor A is: 39.99999999999967
The price per hour in processor B is: 10.0000000000007
The price per hour in processor C is: 20.000000000000057


Solución del problema:
1.b

Se corrige el error generado por el estudiante en el sistema de ecuaciones

In [23]:
A_2 = np.array([[2, 4, 5], [6, 9, 8], [4.2, 5, 3]])
B_2 = np.array([220, 490, 274])
X_2 = np.linalg.inv(A_2).dot(B_2)

In [41]:
# Get the inverse of A
A_inv_2 = np.linalg.inv(A_2)

# Multiply the inverse of A by A
result = np.dot(A_inv_2, A_2)

# Print the result
print(result)

[[ 1.00000000e+00 -1.77635684e-15 -8.88178420e-15]
 [ 1.09314267e-16  1.00000000e+00  8.88178420e-15]
 [ 1.29810692e-15 -8.88178420e-16  1.00000000e+00]]


In [33]:
x_2 = np.linalg.inv(A_2).dot(B_2)
x_2

array([20.        , 31.53846154, 10.76923077])

In [28]:
print("The price per hour in processor A is:", x_2[0])
print("The price per hour in processor B is:", x_2[1])
print("The price per hour in processor C is:", x_2[2])

The price per hour in processor A is: 20.00000000000013
The price per hour in processor B is: 31.538461538461764
The price per hour in processor C is: 10.769230769230754


Ahora vamos a calcular el error relativo de A 

In [13]:
def relative_error(x, y):
    return abs(x - y) / abs(y)

In [14]:
x = 39.99999999999967
y = 20.00000000000013
error = relative_error(x,y)
print(error)

0.9999999999999705


Ahora vamos a calcular el error relativo de B

In [15]:
x = 10.0000000000007
y = 31.538461538461764
error = relative_error(x,y)
print(error)

0.6829268292682728


Ahora vamos a calcular el error relativo de c

In [16]:
x = 20.000000000000057
y = 10.769230769230754
error = relative_error(x,y)
print(error)

0.8571428571428651


La condición de una matriz, también conocida como número de condición, es una medida que se utiliza en el campo del análisis numérico para evaluar cuán sensible es una matriz a pequeños cambios en sus elementos o en sus términos de entrada

Debemos de generar la condición de la matriz A y para esto debemos de hallar la norma de A

||A|| * ||A^(-1)||

In [67]:
Norma_A_1 = np.linalg.norm(A_1, ord=np.inf)
Norma_A_1

23.0

In [69]:
Norma_inv_A = np.linalg.norm(A_inv_1, ord=np.inf)
Norma_inv_A

33.307692307692335

In [70]:
condicion_A = Norma_A_1 * Norma_inv_A
condicion_A

766.0769230769237

La cota superior superior para el error relativo seria:
(∥x∥ / ∥Δx∥) ≤κ(A) * (∥ΔA∥/∥A∥)
siendo k(A) = condicion​

Sacando la diferencia entre A_1 y A_2 tenemos 

In [71]:
diferencia_As = A_1 - A_2 
diferencia_As

array([[ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [-0.1,  0. ,  0. ]])

La cuota superior seria

In [77]:
diferencia_As[]

array([[ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [-0.1,  0. ,  0. ]])

In [83]:
cota_superior = diferencia_As[2:3]
cota_superior

array([[-0.1,  0. ,  0. ]])

In [84]:
cota = condicion_A*(0.1/Norma_A_1)
cota

3.330769230769233