In [1]:
import numpy as np

## Matrices triangulares con A = LU

In [2]:
A = np.array([[ 3. , -0.1, -0.2],
              [ 0.1,  7. , -0.3],
              [ 0.3, -0.2, 10. ]], dtype=float)

B = np.array([7.85,-19.3,71.4], dtype=float)

In [3]:
# A = np.array([[ 1.0, 0.0, 0.0],
#               [ 0.03333333, 1.0, 0.0],
#               [ 0.1, -0.02712994, 1.0 ]], dtype=float)

# B = np.array([20.0, 31.538461538461764, 10.769230769230754], dtype=float)

In [4]:
# PROCEDIMIENTO
B  = np.transpose([B]) # Se transpone el vector para poder hacer la concatenación con la matriz
AB = np.concatenate((A,B),axis=1) # Se concatena la matriz con el vector
AB = np.copy(AB) # Se genera una copia de la matriz aumentada

In [5]:
# Pivoteo parcial por filas
tamano = np.shape(AB)
n = tamano[0]
m = tamano[1]

Luego debemos de intercambiar las filas en la matriz extendida AB para asegurarse de que el elemento en la posición, i,i (el pivote) sea el mayor en valor absoluto en su columna. Esto ayuda a evitar divisiones por cero y mejora la estabilidad numérica del algoritmo de eliminación hacia adelante.

In [6]:
# Para cada fila en AB
for i in range(0,n-1,1):  # Para cada fila en AB, se comienza desde la primer fila hasta la penultima fila

    # columna desde diagonal i en adelante
    columna = abs(AB[i:,i])  # Se optine la columna correspondiente al pivote en valor absoluto
    dondemax = np.argmax(columna) # Se encuentra la posición del elemento máximo en la columna

    # Si la posición del elemento máximo no es 0(es decir, el elemto máximo no esta en la diagonal), se intercambian las filas i y dondemax + i
    # dondemax no está en diagonal
    if (dondemax !=0):
        # intercambia filas
        temporal = np.copy(AB[i,:])
        AB[i,:] = AB[dondemax+i,:]
        AB[dondemax+i,:] = temporal

AB1 = np.copy(AB)
A1 = np.copy(AB[:,:m-1])
B1 = np.copy(AB[:,m-1])

Realizamos la eliminación hacia adelante en la matriz extendida AB para convertirla en una matriz triangular superior. Al mismo tiempo, se construye una matriz L que contiene los factores de multiplicación utilizados en cada paso de la eliminación hacia adelante. La matriz L es una matriz triangular inferior con unos en la diagonal principal.

In [7]:
# eliminacion hacia adelante
# se inicializa L
L = np.identity(n,dtype=float)
for i in range(0,n-1,1):
    pivote = AB[i,i]
    adelante = i+1
    for k in range(adelante,n,1):
        factor = AB[k,i]/pivote
        AB[k,:] = AB[k,:] - AB[i,:]*factor
        L[k,i] = factor

U = np.copy(AB[:,:m-1])

Por ultimo se optiene U y L: Después de completar la eliminación hacia adelante, las matrices U y L se extraen de la matriz extendida AB. La matriz U es la parte triangular superior de AB sin la última columna, y la matriz 
L es la parte triangular inferior de AB con unos en la diagonal principal.

In [8]:
print('Pivoteo parcial por filas')
print(AB1)
print('eliminación hacia adelante')
print('Matriz U: ')
print(U)
print('matriz L: ')
print(L)

Pivoteo parcial por filas
[[  3.    -0.1   -0.2    7.85]
 [  0.1    7.    -0.3  -19.3 ]
 [  0.3   -0.2   10.    71.4 ]]
eliminación hacia adelante
Matriz U: 
[[ 3.         -0.1        -0.2       ]
 [ 0.          7.00333333 -0.29333333]
 [ 0.          0.         10.01204188]]
matriz L: 
[[ 1.          0.          0.        ]
 [ 0.03333333  1.          0.        ]
 [ 0.1        -0.02712994  1.        ]]


## Metodo con Matrices triangulares A = L.U

In [9]:
A = np.array([[ 3. , -0.1, -0.2],
              [ 0.1,  7. , -0.3],
              [ 0.3, -0.2, 10. ]], dtype=float)

B = np.array([7.85,-19.3,71.4], dtype=float)

In [10]:
B  = np.transpose([B])
AB = np.concatenate((A,B),axis=1)
AB = np.copy(AB)

In [11]:
# Pivoteo parcial por filas
tamano = np.shape(AB)
n = tamano[0]
m = tamano[1]

In [12]:
# Para cada fila en AB
for i in range(0,n-1,1):

    # columna desde diagonal i en adelante
    columna = abs(AB[i:,i])
    dondemax = np.argmax(columna)

    # dondemax no está en diagonal
    if (dondemax !=0):
        # intercambia filas
        temporal = np.copy(AB[i,:])
        AB[i,:] = AB[dondemax+i,:]
        AB[dondemax+i,:] = temporal

AB1 = np.copy(AB)
A1 = np.copy(AB[:,:m-1])
B1 = np.copy(AB[:,m-1])

In [21]:
AB1


array([[  3.  ,  -0.1 ,  -0.2 ,   7.85],
       [  0.1 ,   7.  ,  -0.3 , -19.3 ],
       [  0.3 ,  -0.2 ,  10.  ,  71.4 ]])

In [22]:
A1

array([[ 3. , -0.1, -0.2],
       [ 0.1,  7. , -0.3],
       [ 0.3, -0.2, 10. ]])

In [23]:
B1

array([[  7.85],
       [-19.3 ],
       [ 71.4 ]])

In [13]:
# eliminacion hacia adelante
# se inicializa L
L = np.identity(n,dtype=float)
for i in range(0,n-1,1):
    pivote = AB[i,i]
    adelante = i+1
    for k in range(adelante,n,1):
        factor = AB[k,i]/pivote
        AB[k,:] = AB[k,:] - AB[i,:]*factor
        L[k,i] = factor

U = np.copy(AB[:,:m-1])

In [14]:
# Resolver LY = B   donde Y = B1
B1  = np.transpose([B1])
AB =np.concatenate((L,B1),axis=1)
AB

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         7.85000000e+00],
       [ 3.33333333e-02,  1.00000000e+00,  0.00000000e+00,
        -1.93000000e+01],
       [ 1.00000000e-01, -2.71299381e-02,  1.00000000e+00,
         7.14000000e+01]])

In [15]:
# sustitución hacia adelante
Y = np.zeros(n,dtype=float)
Y[0] = AB[0,n]
for i in range(1,n,1):
    suma = 0
    for j in range(0,i,1):
        suma = suma + AB[i,j]*Y[j]
    b = AB[i,n]
    Y[i] = (b-suma)/AB[i,i]

Y = np.transpose([Y])
Y

array([[  7.85      ],
       [-19.56166667],
       [ 70.08429319]])

In [16]:
# Resolver UX = Y
AB =np.concatenate((U,Y),axis=1)
AB

array([[  3.        ,  -0.1       ,  -0.2       ,   7.85      ],
       [  0.        ,   7.00333333,  -0.29333333, -19.56166667],
       [  0.        ,   0.        ,  10.01204188,  70.08429319]])

In [17]:
# sustitución hacia atrás
ultfila = n-1
ultcolumna = m-1
X = np.zeros(n,dtype=float)

for i in range(ultfila,0-1,-1):
    suma = 0
    for j in range(i+1,ultcolumna,1):
        suma = suma + AB[i,j]*X[j]
    b = AB[i,ultcolumna]
    X[i] = (b-suma)/AB[i,i]

X = np.transpose([X])
X

array([[ 3. ],
       [-2.5],
       [ 7. ]])

In [18]:
# SALIDA
print('Pivoteo parcial por filas: AB')
print(AB1)
print('eliminación hacia adelante')
print('Matriz U: ')
print(U)
print('matriz L: ')
print(L)
print('B1 :')
print(B1)
print('Y Sustitución hacia adelante')
print(Y)
print('X Sustitución hacia atras')
print(X)

Pivoteo parcial por filas: AB
[[  3.    -0.1   -0.2    7.85]
 [  0.1    7.    -0.3  -19.3 ]
 [  0.3   -0.2   10.    71.4 ]]
eliminación hacia adelante
Matriz U: 
[[ 3.         -0.1        -0.2       ]
 [ 0.          7.00333333 -0.29333333]
 [ 0.          0.         10.01204188]]
matriz L: 
[[ 1.          0.          0.        ]
 [ 0.03333333  1.          0.        ]
 [ 0.1        -0.02712994  1.        ]]
B1 :
[[  7.85]
 [-19.3 ]
 [ 71.4 ]]
Y Sustitución hacia adelante
[[  7.85      ]
 [-19.56166667]
 [ 70.08429319]]
X Sustitución hacia atras
[[ 3. ]
 [-2.5]
 [ 7. ]]


# Luego concatenamos U con Y y reemplazamos hacia atras 