In [45]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import plotly_express as px

from numpy import matrix, linalg

In [20]:
import numpy as np

def generate_hilbert_matrix(N):

    hilbert_matrix = np.array([[1 / (i + j - 1) for j in range(1, N + 1)] for i in range(1, N + 1)])
    return matrix(hilbert_matrix)

def calculate_covariance_matrix(hilbert_matrix):

    return np.cov(hilbert_matrix, rowvar=False)

In [53]:


def generate_normal_data(mean, covariance_matrix, num_samples):

    samples = np.random.multivariate_normal(mean, covariance_matrix, num_samples)
    return samples

# Ejemplo de uso:
N = 5  # Tamaño de la matriz de Hilbert
mean = np.zeros(N)  # Vector de medias
hilbert_matrix = generate_hilbert_matrix(N)
covariance_matrix = calculate_covariance_matrix(hilbert_matrix)
num_samples = 1000  # Número de muestras a generar

# Generar datos normales multivariantes
data = generate_normal_data(mean, covariance_matrix, num_samples)

data

array([[-0.33894873, -0.14859236, -0.08759015, -0.05866315, -0.04231312],
       [ 0.3558821 ,  0.11563727,  0.05556018,  0.03202431,  0.02057361],
       [-0.12635353, -0.07336203, -0.04778975, -0.03363753, -0.02498122],
       ...,
       [-0.08163546, -0.05523523, -0.03738585, -0.02674579, -0.02003532],
       [-0.39169698, -0.12625476, -0.06089998, -0.03534751, -0.02287987],
       [ 0.36476749,  0.14642394,  0.08172904,  0.05275364,  0.03705051]])

In [26]:
generate_hilbert_matrix(2)

matrix([[1.        , 0.5       ],
        [0.5       , 0.33333333]])

In [112]:
# Define the range of n values
n_values = np.arange(2, 16)  # n from 2 to 101

# Initialize an empty list to store condition numbers
condition_numbers = []

# Calculate the condition number for each n
for n in n_values:
    hilbert_matrix = generate_hilbert_matrix(n)
    covariance_matrix = calculate_covariance_matrix(hilbert_matrix)
    condition_number = np.linalg.cond(covariance_matrix,p=np.inf)
    condition_numbers.append(condition_number)

# Create a DataFrame with n and condition numbers
data = {'n': n_values, 'Condition Number': condition_numbers}
df = pd.DataFrame(data)

# Create the plot using Plotly Express
fig = px.line(df, x='n', y='Condition Number', title='Condition Number of Hilbert Matrix vs. n')
fig.update_layout(xaxis_title='n', yaxis_title='Condition Number', xaxis_tickformat='d')#, yaxis_tickformat='d')

fig.show()

# 4.2.

In [98]:
#Definiendo el vector con x
x= np.arange(1, 16)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [99]:
H15=generate_hilbert_matrix(15)
H15

matrix([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
         0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
         0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667],
        [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
         0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909,
         0.08333333, 0.07692308, 0.07142857, 0.06666667, 0.0625    ],
        [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714,
         0.125     , 0.11111111, 0.1       , 0.09090909, 0.08333333,
         0.07692308, 0.07142857, 0.06666667, 0.0625    , 0.05882353],
        [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ,
         0.11111111, 0.1       , 0.09090909, 0.08333333, 0.07692308,
         0.07142857, 0.06666667, 0.0625    , 0.05882353, 0.05555556],
        [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
         0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
         0.06666667, 0.0625   

In [109]:
b=H15@x
b
Ib=b.T

print(b)
print(Ib)

[[15.         12.61927101 11.12089495 10.01467577  9.1423747   8.42796838
   7.82784777  7.31430725  6.86852505  6.47709069  6.13010076  5.82003392
   5.5410471   5.28851531  5.05871941]]
[[15.        ]
 [12.61927101]
 [11.12089495]
 [10.01467577]
 [ 9.1423747 ]
 [ 8.42796838]
 [ 7.82784777]
 [ 7.31430725]
 [ 6.86852505]
 [ 6.47709069]
 [ 6.13010076]
 [ 5.82003392]
 [ 5.5410471 ]
 [ 5.28851531]
 [ 5.05871941]]


In [ ]:
b2=x@H15

In [104]:
I_H15=np.linalg.inv(H15)
I_H15

matrix([[ 1.58102325e+02, -1.23889847e+04,  3.15964881e+05,
         -3.86891496e+06,  2.67618553e+07, -1.13312251e+08,
          3.03708680e+08, -5.10569864e+08,  4.93534545e+08,
         -1.71580270e+08, -1.43728572e+08,  1.60546278e+08,
         -2.04394795e+07, -3.37170153e+07,  1.23612882e+07],
        [-1.24139480e+04,  1.29893443e+06, -3.73711517e+07,
          4.90142708e+08, -3.55249071e+09,  1.55982784e+10,
         -4.31721807e+10,  7.49844614e+10, -7.54267804e+10,
          2.83167578e+10,  2.32445585e+10, -3.12735169e+10,
          1.04566898e+10,  1.57293115e+09, -1.20276845e+09],
        [ 3.18072012e+05, -3.75526038e+07,  1.15731114e+09,
         -1.59009456e+10,  1.19424887e+11, -5.40541259e+11,
          1.53971946e+12, -2.75663156e+12,  2.87538197e+12,
         -1.14181680e+12, -9.68567378e+11,  1.49246049e+12,
         -7.14620031e+11,  9.37033423e+10,  1.62678082e+10],
        [-3.92638714e+06,  4.96768669e+08, -1.60423758e+10,
          2.28401603e+11, -1.76741998

In [110]:
b@I_H15

matrix([[  1.00000084,   2.00009537,   2.99893188,   4.09765625,
           4.86914062,  10.71875   ,   6.        ,  36.        ,
          -4.        ,  35.        ,  61.        , -49.        ,
         107.75      , -17.375     ,  17.3125    ]])

In [103]:
import numpy as np
from scipy.linalg import hilbert

# Definir el tamaño de la matriz de Hilbert
n = 15

# Crear la matriz de Hilbert de tamaño 15x15
H = hilbert(n)

# Crear el vector b
x = np.arange(1, n + 1)  # [1, 2, 3, ..., 15]
b = np.dot(H, x)

# Resolver el sistema lineal x = H^(-1) * b
x_estimated = np.linalg.solve(H, b)

# Imprimir la solución estimada
print("Solución estimada:", x_estimated)

Solución estimada: [  0.99999951   2.00007576   2.99712233   4.04722415   4.58549494
   8.14944695   0.18557238  20.63897678  -0.6744124   -2.16371952
  53.6820964  -42.3648982   51.00101332  -0.41395869  17.32996634]
